---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
# Keycloak secrets
# KC_DB_PASSWORD: keycloak user on keycloak_db
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: auth
type: Opaque
stringData:
  # value to fill in before apply (placeholder)
  KEYCLOAK_ADMIN_PASSWORD: "CHANGE_ME_password"
  KC_DB_PASSWORD: "CHANGE_ME_password"
  LDAP_BIND_PASSWORD: "CHANGE_ME_ldap_bind_password"
