#!/usr/bin/env bash
# OPTAVIM: sync the branding sources into the K8s ConfigMap.
# Regenerates 04-branding-cm.yaml from branding/optavim-{icon,logo}.svg + optavim.css
set -euo pipefail

cd "$(dirname "$0")/.."
SRC=branding
DST=04-branding-cm.yaml

[ -f "$SRC/optavim-icon.svg" ] || { echo "MISSING $SRC/optavim-icon.svg"; exit 1; }
[ -f "$SRC/optavim-logo.svg" ] || { echo "MISSING $SRC/optavim-logo.svg"; exit 1; }
[ -f "$SRC/optavim.css" ]      || { echo "MISSING $SRC/optavim.css"; exit 1; }

kubectl create configmap grafana-branding \
  --namespace=monitoring \
  --from-file=optavim-icon.svg=$SRC/optavim-icon.svg \
  --from-file=optavim-logo.svg=$SRC/optavim-logo.svg \
  --from-file=optavim.css=$SRC/optavim.css \
  --dry-run=client -o yaml > $DST.tmp

# Prepend doc header + labels
cat > $DST <<EOF
---
##############################################################################
# OPTAVIM Grafana branding ConfigMap (auto-generated by branding/sync.sh)
# Do not edit by hand: edit branding/optavim-{icon,logo}.svg
# or branding/optavim.css then re-run this script.
##############################################################################
EOF
# Inject labels via sed (kubectl create has no clean --labels for files)
sed -e 's/^metadata:$/metadata:\n  labels:\n    app: grafana\n    project: optavim\n    component: branding/' \
    $DST.tmp >> $DST
rm $DST.tmp

echo "Generated $DST"
echo "Apply with: kubectl apply -f $DST && kubectl rollout restart deploy/grafana -n monitoring"
