apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-deployment.yaml
  - 04-branding-cm.yaml
  - 05-dashboards-cm.yaml
  - 06-ingressroute.yaml
