apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv-galera-0.yaml
  - pv-galera-1.yaml
  - pv-galera-2.yaml
  - pv-grafana.yaml
  - pv-prometheus.yaml
  - pv-wazuh-indexer.yaml
  - pv-wazuh-manager.yaml
