apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-wazuh-indexer
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: 10.1.30.100
    path: /data/exports/wazuh-idx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wazuh-indexer
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
