apiVersion: v1
kind: Secret
metadata:
  name: dolibarr-secret
  namespace: apps
  labels:
    app: dolibarr
    project: optavim
type: Opaque
stringData:
  DOLI_DB_PASSWORD: "CHANGE_ME_password"
  DOLI_ADMIN_PASSWORD: "CHANGE_ME_password"
  OIDC_CLIENT_SECRET: "CHANGE_ME_password"
