apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dolibarr-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: 10.1.30.100
    path: /data/exports/dolibarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-dolibarr-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
