#!/usr/bin/env bash
# OPTAVIM: sync the JSON dashboards into the K8s ConfigMap.
# Regenerates 05-dashboards-cm.yaml from dashboards/*.json
set -euo pipefail

cd "$(dirname "$0")/.."
SRC=dashboards
DST=05-dashboards-cm.yaml

DASHBOARDS=$(ls $SRC/*.json 2>/dev/null | grep -v "/sync\.sh$" || true)
if [ -z "$DASHBOARDS" ]; then
  echo "ERR: no *.json in $SRC/"
  exit 1
fi

# kubectl create configmap does the right encoding for the JSON files
KUBECTL_ARGS=""
for f in $DASHBOARDS; do
  KUBECTL_ARGS="$KUBECTL_ARGS --from-file=$f"
done

kubectl create configmap grafana-dashboards-optavim \
  --namespace=monitoring \
  $KUBECTL_ARGS \
  --dry-run=client -o yaml > $DST.tmp

# Header + inject labels
cat > $DST <<EOF
---
##############################################################################
# OPTAVIM Grafana dashboards ConfigMap (auto-generated by dashboards/sync.sh)
# Do not edit by hand: edit dashboards/*.json then re-run sync.sh
##############################################################################
EOF
sed -e 's/^metadata:$/metadata:\n  labels:\n    app: grafana\n    project: optavim\n    component: dashboards/' \
    $DST.tmp >> $DST
rm $DST.tmp

COUNT=$(echo "$DASHBOARDS" | wc -l | tr -d ' ')
echo "Generated $DST with $COUNT dashboards"
echo "Apply with: kubectl apply -f $DST"
echo "Grafana picks up changes within 30s (provider updateIntervalSeconds: 30)"
