# ClusterAdcsIssuer: the whole cluster can request certificates
# via cert-manager (Certificate) -> adcs-issuer -> AD CS DC-01.
#
# The caBundle holds the AD CS root certificate.
# To regenerate it:
#   openssl s_client -showcerts -connect 10.1.20.1:636 </dev/null \
#     | openssl x509 | base64 -w0
apiVersion: adcs.certmanager.csf.nokia.com/v1
kind: ClusterAdcsIssuer
metadata:
  name: adcs-optavim
spec:
  url: http://10.1.20.1/certsrv
  templateName: WebServer
  retryInterval: 1h
  statusCheckInterval: 6h
  credentialsRef:
    name: adcs-issuer-credentials
  # Root certificate `optavim-DC-AD-DC-01-CA` (valid until 2031-03-21)
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEZXpDQ0FtT2dBd0lCQWdJUVJCMW5kYUMvMnFOSlZNQTE2NHRwRmpBTkJna3Foa2lHOXcwQkFRc0ZBREJRDQpNUlF3RWdZS0NaSW1pWlB5TEdRQkdSWUVZMjl5Y0RFWE1CVUdDZ21TSm9tVDhpeGtBUmtXQjI5d2RHRjJhVzB4DQpIekFkQmdOVkJBTVRGbTl3ZEdGMmFXMHRSRU10UVVRdFJFTXRNREV0UTBFd0hoY05Nall3TXpJeE1UZzBNekEwDQpXaGNOTXpFd016SXhNVGcxTXpBeldqQlFNUlF3RWdZS0NaSW1pWlB5TEdRQkdSWUVZMjl5Y0RFWE1CVUdDZ21TDQpKb21UOGl4a0FSa1dCMjl3ZEdGMmFXMHhIekFkQmdOVkJBTVRGbTl3ZEdGMmFXMHRSRU10UVVRdFJFTXRNREV0DQpRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3pXUlFYeE5wWFJSb1R6RDdiDQoxYnY4UFJWRWVIUVduOHNYMUJ1ZWtXcUpnU3dvT04wOXpNdlhCbm1HRHJ2S0Z6bVR2ZWpTK3pGcEluK2JzRVg5DQo0SFRhd0ZEZm1KSnBybVBQbGV3dnZPbk1PVHExUUNZOFNqSDJPL0kycW9BbHhiRFN2Wmk1cVVYRkxMN1NaakpqDQpFOUI3UkJBOFF0cGtkT2JkL1YxcmRycExHRXV1cGRIbjJvNExvSExRZnlsVlljTFNFRGFVWWdyQ1RqUTBnaWkrDQpPdnpFVHdnSzVyS3BCcmJKaDQvSGhTUlAyVm9WWVZlek1iOE5pTG0vVHU1emh6eGVNZTlvQ25LekU0RDd1S3Y1DQoxTldzMlh4L2xQcWkyeDhCejhZcGk1Z2p6Zm9FS3cwN1dqZDBFRXkyL25ZdnVpN0VobE0wK3hsQnZibENJQWxlDQpKRkUxQWdNQkFBR2pVVEJQTUFzR0ExVWREd1FFQXdJQmhqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkDQpEZ1FXQkJSWEw5WDllK0JVK0dhN2gyRkVOaUZKYk90SjNEQVFCZ2tyQmdFRUFZSTNGUUVFQXdJQkFEQU5CZ2txDQpoa2lHOXcwQkFRc0ZBQU9DQVFFQWtBK1FnNmRQL2tueCtsWWwyc3RYeHZWOUpmN1RSaXJscTQ5ZTI1YzFjamptDQoyZXFMOFVTNGcwRGM0cVFQN0ZlZjR5N00vYkZsS0pweElKZWlRYlFwR0F5UFM1YlFOSXFyT2c1d2JQR1JVMXpJDQpRMG5JVFpLUGc0RFpyRkk1WEptUndVZy9Nb1R6ZXVYK1BxcmhDYlpvNlZMMzQ5YkFybDBiSHQ5NTlhT2JPVjlkDQpBRFlHbzN4SkRSanlDekt4b21lS3N2Umx2R3pKbTE1b1AyV054aTlrejNoSGNlVTRiWU5MSTN4MEh3bjg5YmhuDQpYTzhseFJuNTZVTEhQZlNXSm0rcUszVVR4enVRbUh3YUV5VHo4RHRCWlpMcTNwOG9sNi9GYWlUakw2NXRvaEdrDQp3SVd3L2xVSE1kczRsT3JWeVA2ZWZuNEFTUllTUU1CMFFvU29lR3ZZZXc9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
